apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: ${{values.component_id}}
  name: ${{values.component_id}}
spec:
  endpoints:
  - interval: 30s
    port: prometheus
    scheme: http
    path: /metrics
  selector:
    matchLabels:
      app: ${{values.component_id}}
