apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: v1beta3-fuse-springboot
  title: Red Hat Integration Fuse on Spring Boot Template
  description: Scaffolder v1beta3 template for Fuse on Spring Boot
  tags:
    - recommended
    - java
    - camel
    - springboot
    - maven
spec:
  owner: backstage/integration-core
  type: service
  parameters:
    - title: Maven Project information
      required:
        - component_id
        - owner
        - java_package_name
      properties:
        component_id:
          title: Name
          type: string
          description: Name of the project
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Description
          default: 'Fuse on Spring Boot project'
        group_id:
          title: Maven Group ID
          type: string
          description: Maven Group ID
          default: 'com.redhat'
        artifact_id:
          title: Maven Artifact ID
          type: string
          description: Maven Artifact ID
          default: 'fuse'
        artifact_version:
          title: Maven Artifact Version
          type: string
          description: Maven Artifact Version
          default: '1.0-SNAPSHOT'
        java_package_name:
          title: Java Package Name
          type: string
          description: Name for the java package
          default: 'com.redhat.fuse'
        owner:
          title: Owner
          type: string
          description: IdP owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Apache Camel Features
      required:
        - fuse_version
        - features
      properties:
        fuse_version:
          title: Fuse Version
          type: string
          description: The Fuse Version to be used
          default: 7.11.0.fuse-sb2-7_11_0-00028-redhat-00001
          enum:
            - 7.11.0.fuse-sb2-7_11_0-00028-redhat-00001
          enumNames:
            - 7.11
          ui:widget: radio
        features:
          title: Select features
          type: array
          items:
            type: string
            enum:
              - AMQP
              - CXF
              - JPA
              - SQL
          uniqueItems: true
          ui:widget: checkboxes
      dependencies:
        features:
          oneOf:
            - properties:
                features:
                  items:
                    enum:
                      - JPA
                database_type:
                  title: Database
                  type: string
                  description: The database to be used
                  default: postgresql
                  enum:
                    - postgresql
                    - mysql
                    - mariadb
                  enumNames:
                    - 'PostgreSQL'
                    - 'MySQL'
                    - 'MariaDB'
                  ui:widget: radio
                database_name:
                  title: Database Name
                  type: string
                  description: Database Name 
                  default: database
                database_user:
                  title: Database User
                  type: string
                  description: Database User
                  default: 'user'
                database_user_password:
                  title: Database User Password
                  type: string
                  description: Database User Password
                  default: 'password'
                required:
                  - database_type
                  - database_name
                  - database_user
                  - database_user_password
#            - properties:
#                features:
#                   items:
#                     enum:
#                       - AMQP
#                 amqp_broker_host:
#                   title: AMQP Broker
#                   type: string
#                   description: The AMQP Broker to be used
#                   default: amq-broker-hdls-svc
#                 amqp_broker_port:
#                   title: AMQP Broker Port
#                   type: string
#                   description: AMQP Broker Port
#                   default: 5672
#                 amqp_broker_user:
#                   title: AMQP Broker User
#                   type: string
#                   description: AMQP Broker User
#                   default: 'admin'
#                 amqp_broker_user_password:
#                   title: AMQP Broker User Password
#                   type: string
#                   description: AMQP Broker User Password
#                   default: 'admin'
#                 required:
#                   - amqp_broker_host
#                   - amqp_broker_port
#                   - amqp_broker_user
#                   - amqp_broker_user_password
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: template
      name: Generating component
      action: fetch:template
      input:
        url: ./skeleton
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          group_id: ${{ parameters.group_id }}
          artifact_id: ${{ parameters.artifact_id }}
          java_package_name: ${{ parameters.java_package_name }}
          owner: ${{ parameters.owner }}
          organization: ${{ (parameters.repoUrl | parseRepoUrl).owner }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          http_port: 8080
    - id: template-persistence
      if: ${{ parameters.features }}
      name: Generating Persistence Resources
      action: fetch:template
      input:
        url: ./persistence
        copyWithoutRender: []
        values:
        targetPath: ./src/main/resources/META-INF
    - id: publish
      name: Publishing to Source Code Repository
      action: publish:github
      input:
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        repoVisibility: public
    - id: register
      name: Registering to the Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"
  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
