apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.project_slug}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - recommended
    - java
    - camel
    - springboot
    - maven
spec:
  type: website
  lifecycle: experimental
  owner: ${{values.owner | dump}}
